name: Release

on:
  push:
    branches:
    - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/UseCase.sln

      - name: Build project
        run: dotnet build ./src/UseCase.sln --configuration Release

      - name: Test
        run: dotnet test ./src/UseCase.Tests/ -c Release --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover 

      - name: Create Test Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        with:
          label: Unit Test Coverage
          color: brightgreen
          path: ./src/UseCase.Tests/TestResults/coverage.opencover.xml
          gist-filename: use-case-lib-coverage.json
          gist-id: 790517b6b21bfc7cd874a02927141ede
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}

      - name: Print code coverage
        run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"

      - name: Print badge data
        run: echo "Badge data ${{steps.create_coverage_badge.outputs.badge}}"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.3
        with:
          reports: ./src/UseCase.Tests/TestResults/coverage.opencover.xml
          targetdir: coveragereport
          reporttypes: Html_Dark;Badges

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coveragereport