name: Release

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/UseCase.sln

      - name: Build project
        run: dotnet build ./src/UseCase.sln --configuration Debug
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./src/UseCase/bin/Release/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./src/UseCase/bin/Release/

      - name: Test
        run: dotnet test --configuration Release -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal ./src/UseCase.Tests/

      - name: Create Test Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        with:
          label: Unit Test Coverage
          color: brightgreen
          path: UseCase.Tests/TestResults/coverage.opencover.xml
          gist-filename: use-case-lib-coverage.json
          gist-id: 790517b6b21bfc7cd874a02927141ede
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}

      - name: Print code coverage
        run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"

      - name: Print badge data
        run: echo "Badge data ${{steps.test_step.outputs.badge}}"
