name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/UseCase.sln

      - name: Build project
        run: dotnet build ./src/UseCase.sln --configuration Release

      - name: Test
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal UseCase.Tests/
      
      - name: Create Test Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        with:
          label: Unit Test Coverage
          color: brightgreen
          path: UseCase.Tests/TestResults/coverage.opencover.xml
          gist-filename: use-case-lib-coverage.json
          gist-id: 790517b6b21bfc7cd874a02927141ede
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       

      - name: Print code coverage
        run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"

      - name: Print badge data
        run: echo "Badge data ${{steps.test_step.outputs.badge}}"

      - name: Pack NuGet package
        run: dotnet pack ./src/UseCase.sln --configuration Release -o ./lib/release

      - name: List contents of release directory
        run: ls -R ./lib/release

      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push lib/release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
