name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/UseCase.sln

      - name: Build project
        run: dotnet build ./src/UseCase.sln --configuration Release

      - name: Pack NuGet package
        run: dotnet pack ./src/UseCase.sln --configuration Release

      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json
