name: Pull Request Release Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/UseCase.sln

      - name: Build project
        run: dotnet build ./src/UseCase.sln --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
      - name: Test
        run: dotnet test ./src/UseCase.Tests/